# Generated by Django 4.2.7 on 2024-02-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
